Remote Attachment Codec - WIP
xmtp/xmtp-flutter pull request #105
Opened 2023-12-19 17:46 UTC by giovasdistillery

### Expectations
- Adding new codec to Flutter SDK to enable read remote attachments

2024-01-20 00:00 UTC, dmccartney requested changes

2024-01-20 00:00 UTC, dmccartney commented on lib/src/content/encoded_content_ext.dart
> +    return Client.codecs.decode(encodedContent);
This doesn't belong here. 

Instead it should live inside of `CodecRegistry` (and possible `encode` if we want to send w/ it too).
e.g. once you have an implementation of `_decompress` you would use it inside `CodecRegistry.decode`:
```dart
  Future<DecodedContent> decode(xmtp.EncodedContent encoded) async {
      var codec = _codecFor(encoded.type);
      if (codec == null) {
        if (encoded.hasFallback()) {
          return DecodedContent(contentTypeText, encoded.fallback);
        }
        throw StateError(
            "unable to decode unsupported type ${_key(encoded.type)}");
      }
-     return DecodedContent(encoded.type, await codec.decode(encoded));
+     var decompressed = _decompress(encoded);
+     return DecodedContent(decompressed.type, await codec.decode(decompressed));
  }
```

2024-01-23 21:34 UTC, giovasdistillery commented on lib/src/client.dart
> +  static CodecRegistry get codecs => _codecRegistry;
The main problem with that change is that if Client doesn't contain the proper codecs registered at the moment of trying to decode then it will fail, the only way to create a Client object is from a wallet or conversation, in Android and iOS is completely different, is possible to register codecs statically, I was trying to do the same as Android and iOS do. I will create a codec registry in that method, otherwise if I try to use the actual `_codecs` variable in `Client` is not possible to access from that point of the code and I will need to move it to a different level and again is going to be different from the other mobile implementations. 

Please check
https://github.com/xmtp/xmtp-android/blob/main/library/src/main/java/org/xmtp/android/library/codecs/ContentCodec.kt


https://github.com/xmtp/xmtp-android/pull/45/files

in Everywhere there is a way to register a codec using `Client.register` (static way) or getting the codecs of the `Client` object.

if still my last changes are not good for you, please let me know and have a meeting to discuss the proper approach in order to make the change as you want :)

2024-02-03 00:49 UTC, dmccartney commented
I'm going to pick this up and get it merged in a series of forthcoming PRs -- thank you for putting this together!

(First PR is up w/ just the compression bits: https://github.com/xmtp/xmtp-flutter/pull/115)

2024-02-03 00:49 UTC, closed without merging