Update README in preparation for GA
xmtp/xmtp-flutter pull request #45
Opened 2023-02-09 01:29 UTC by jhaaaa

2023-02-09 01:29 UTC, jhaaaa commented on README.md
> +XMTP communicates about breaking revisions in the [XMTP Discord community](https://discord.gg/xmtp), providing as much advance notice as possible. Additionally, breaking revisions in an `xmtp-flutter
True about the Releases page?

2023-02-09 01:47 UTC, jhaaaa commented on README.md
> +> This package does not currently include the `streamAllMessages()` functionality from the [XMTP client SDK for JavaScript](https://github.com/xmtp/xmtp-js) (xmtp-js).
Still true, correct @dmccartney? Just making sure. =)

2023-02-09 01:53 UTC, jhaaaa commented on README.md
> +> This package does not currently include the `streamAllMessages()` functionality from the [XMTP client SDK for JavaScript](https://github.com/xmtp/xmtp-js) (xmtp-js).
@yash-luna ... look what I found: https://github.com/community/community/discussions/16925. Closest thing we're going to get to a callout in GitHub README markdown from what I can tell. WDYT? <3

2023-02-17 07:35 UTC, dmccartney commented on README.md
> +> This package does not currently include the `streamAllMessages()` functionality from the [XMTP client SDK for JavaScript](https://github.com/xmtp/xmtp-js) (xmtp-js).
Confirmed!

2023-02-17 07:36 UTC, dmccartney approved these changes

2023-02-18 00:17 UTC, jhaaaa commented on README.md
> +XMTP communicates about breaking revisions in the [XMTP Discord community](https://discord.gg/xmtp), providing as much advance notice as possible. Additionally, breaking revisions in an `xmtp-flutter
I think it is safe to keep this as-is. We can iterate as the direction we need to take becomes clearer.

2023-02-21 19:05 UTC, dmccartney requested changes

2023-02-21 19:05 UTC, dmccartney commented on README.md
> +
suggestion:
> The example app includes a demonstration of how you might approach caching (offline storage). But beware: the demo app naively performs a full refresh very frequently -- this causes slowdowns. The underlying `xmtp-flutter` client SDK itself has no performance issues. But app developers wanting offline storage will need to design their refresh-strategies for performance. Future versions aim to make this aspect easier to manage.

2023-02-21 19:05 UTC, dmccartney commented on example/README.md
> +
ditto suggestion above ^

2023-02-21 20:29 UTC, yash-luna reviewed
How are we surfacing the typedocs in xmtp.org? 

There was discussion around how the docs won't be on .org but we'll provide a link to the docs and allow searching via Algolia

2023-02-22 18:49 UTC, jhaaaa commented on README.md
> +
@dmccartney Thank you for this - how does my implementation above look to you? Just made a few tech writer nit edits. <3

2023-02-22 18:50 UTC, jhaaaa commented on example/README.md
> +
@dmccartney Thank you for this - how does my implementation above look to you? Just made a few tech writer nit edits. <3

2023-02-23 02:18 UTC, dmccartney approved these changes

2023-02-23 16:47 UTC, jhaaaa commented
@yash-luna I know we discussed in slack, but sharing here as well if others are interested. 

Here is a PR of the doc updates that we'll make on xmtp.org to surface the xmtp-flutter quickstart and reference docs: https://github.com/xmtp/xmtp-dot-org/pull/262

2023-04-05 19:18 UTC, merged